services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails db:prepare && bin/rails server -b 0.0.0.0"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      KEYCLOAK_HOST: keycloak

  keycloak:
    image: quay.io/keycloak/keycloak
    command:
      - start-dev
    environment:
      KC_DB: ${KC_DB}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    extra_hosts:
      - "localhost:host-gateway"
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  pg_data:
  keycloak_data:
